package com.mahuahudong.mvvm;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.mahuahudong.mvvm.databean.UserEventBean;

import com.mahuahudong.mvvm.UserEventBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userEventBeanDaoConfig;

    private final UserEventBeanDao userEventBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userEventBeanDaoConfig = daoConfigMap.get(UserEventBeanDao.class).clone();
        userEventBeanDaoConfig.initIdentityScope(type);

        userEventBeanDao = new UserEventBeanDao(userEventBeanDaoConfig, this);

        registerDao(UserEventBean.class, userEventBeanDao);
    }
    
    public void clear() {
        userEventBeanDaoConfig.clearIdentityScope();
    }

    public UserEventBeanDao getUserEventBeanDao() {
        return userEventBeanDao;
    }

}
