package com.mahuahudong.mvvm;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.mahuahudong.mvvm.databean.VideoHistoryBean;

import com.mahuahudong.mvvm.VideoHistoryBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig videoHistoryBeanDaoConfig;

    private final VideoHistoryBeanDao videoHistoryBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        videoHistoryBeanDaoConfig = daoConfigMap.get(VideoHistoryBeanDao.class).clone();
        videoHistoryBeanDaoConfig.initIdentityScope(type);

        videoHistoryBeanDao = new VideoHistoryBeanDao(videoHistoryBeanDaoConfig, this);

        registerDao(VideoHistoryBean.class, videoHistoryBeanDao);
    }
    
    public void clear() {
        videoHistoryBeanDaoConfig.clearIdentityScope();
    }

    public VideoHistoryBeanDao getVideoHistoryBeanDao() {
        return videoHistoryBeanDao;
    }

}
